#!/bin/sh
set -e

ln -sf "$PWD/.exrc" "$HOME/.exrc"
ln -sf "$PWD/.vimrc" "$HOME/.vimrc"
ln -sf "$PWD/.bashrc" "$HOME/.bashrc"
ln -sf "$PWD/.inputrc" "$HOME/.inputrc"
ln -sf "$PWD/.tmux.conf" "$HOME/.tmux.conf"
ln -sf "$PWD/.gitconfig" "$HOME/.gitconfig"
ln -sf "$PWD/.bash_profile" "$HOME/.bash_profile"
